name: 'Install dependencies'
description: 'Install dependencies for the project'
inputs:
  WEATHER_API_KEY:
    description: 'Weather API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create .env file
      shell: bash
      run: |
        touch .env
        echo WEATHER_API_KEY=${{ inputs.WEATHER_API_KEY }} >> .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
