name: 'Install dependencies'
description: 'Install dependencies for the project'
runs:
  using: 'composite'
  steps:
    - name: Copy .env file
      shell: bash
      run: cp .env.template .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
