name: Unit Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
        with:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

      - name: Run TypeScript
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: yarn tsc --noEmit

      - name: Run ESLint
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: yarn lint

      - name: Run Unit Tests
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: yarn test
